config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  resources :equipments

  devise_for :users
  
  get 'parks/search'
  post 'parks/search'

  resources :parks do
    resources :comments
  end

 

  root 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

	belongs_to :park
	has_one :user

	validates :comment, length: { minimum: 5 }
end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
  has_many :park_equipments
  has_many :parks, through: :park_equipments

  validates_presence_of :name, :age_range
  validates :description, length: { minimum: 5 }
end

app/models/park.rb
class Park < ActiveRecord::Base
	geocoded_by :full_street_address
	after_validation :geocode

	has_many :comments
	has_many :users
	has_many :park_equipments
	has_many :equipments, through: :park_equipments 

	validates_presence_of :name, :address, :city, :state

	def full_street_address
		"#{address}, #{city}, #{state}"
	end

end

app/models/park_equipment.rb
class ParkEquipment < ActiveRecord::Base
	belongs_to :park
	belongs_to :equipment
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :comments

   validates_presence_of :username
    validates :username, uniqueness: true

  def admin?
    admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.


  def authorize_user!
  	authenticate_user!

  	unless user_signed_in?
  		redirect_to root_path, alert: "Access Denied."
  	end
  end


  protected
  def configure_permitted_parameters
	  devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password) }
	end

  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!, only: [:create]
	before_action :authorize_admin!, only: [:delete]

	def create
		@park = Park.find(params[:park_id])
		# @comment = Comment.joins(parks: [{comments: @user}, :park_id]).create(comment_params)
		@comment = @park.
			comments.create(
				comment_params.merge(user_id: current_user.id)
				)
		redirect_to park_path(@park)
		
	end

	def destroy
		@park = Park.find(params[:park_id])
		@comment = @park.comments.find(params[:id])
		@comment.destroy

		redirect_to park_path(@park)
	end

	private
	def comment_params
		params.require(:comment).permit(:comment, :user_id, :park_id)
	end
end

app/controllers/equipments_controller.rb
class EquipmentsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@equips = Equipment.all
	end

	def new
		@equip = Equipment.new
	end

	def create
		@equip = Equipment.new(equip_params)
		if @equip.save
			redirect_to equipment_path(@equip)
		else
			render :new
		end
	end

	def show 
		@equip = Equipment.find(params[:id])
	end

	def edit
		@equip = Equipment.find(params[:id])
	end

	def update
		@equip = Equipment.find(params[:id])
		if @equip.update(equip_params)
		else
			render :edit
		end
		redirect_to @equip
	end

	def destroy
		@equip = Equipment.find(params[:id])
		@equip.destroy
		redirect_to equipment_path
	end

	private
		def equip_params
			params.require(:equipment).permit(:name, :description, :age_range)
		end

end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]


	def index
		if params[:button].present?
			location = request.ip
			unless location == "127.0.0.1"
				@parks = Park.near(location.ip, 5 || 4, order: :distance)
			else
				@request = "You cannot 'Find Me' on a local server (#{location}), sorry."
			end
		end
		if params[:location].present?
			unless params[:distance].present?
				params[:distance] = 5
			end
			@parks = Park.near(params[:location], params[:distance] || 4, order: :distance)
			if @parks.length == 0
				@message = "Have you tried to search for City without State?"
			else
				params[:location] = nil
				params[:distance] = nil
			end
		else	
			@parks = Park.all
		end
	end

	def new
		@park = Park.new
	end

	def create
		@park = Park.new(park_params)
		if @park.save
			redirect_to park_path(@park)
		else
			render :new
		end
	end

	def show
		@park = Park.find(params[:id])
		@users = User.all
		@zoom = 16 #default
	end

	def edit
		@park = Park.find(params[:id])
	end

	def update
		@park = Park.find(params[:id])
		if @park.update(park_params)
		else
			render :edit
		end
		redirect_to @park
	end

	def destroy
		@park = Park.find(params[:id])
		@park.destroy

		redirect_to parks_path
	end

	# def search
	# 	@parksearch = "this"
	# 	redirect_to parks_path
	# end

	private
		def park_params
			params.require(:park).permit(:name, :address, 
																		:city, :state, :description,
																		{equipment_ids:[]} )
		end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/equipments_helper.rb
module EquipmentsHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
" <%= comment.comment %> " said: 
<% @users.each do |user| %>
	<% if user.id == comment.user_id %>
		<strong class="username"><%= user.username %></strong>
	<% end %>
<% end %>
<% if user_signed_in? %>
	<% if current_user.id == comment.user_id || current_user.admin?%>
			<%= link_to 'Delete Comment', [comment.park, comment], method: :delete,
		data: {confirm: "Are you sure?"} %>
	<% end %>
<% end %>
</p>
 

app/views/comments/_form.html.erb
<%= form_for([@park, @park.comments.build]) do |f| %>
<p>
<%= f.label :comment %><br>
<%= f.text_area :comment, size: "60x20" %>
</p>
<p>
		<%= f.submit %>
</p>
<% end %>

app/views/equipments/_form.html.erb
<% if @equip.errors.any? %>
		<div id="error_explanation">
			<h2><%=pluralize(@equip.errors.count, "error") %> prohibited
			this equipment from being saved:</h2>
			<ul>
				<% @equip.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

<%= form_for @equip do |f| %>
<ul>
	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>

	<div class="form-group">
	<%= f.label :age_range %>
	<%= f.text_field :age_range %>
	</div>

	<div class="form-group">
		<%= f.label :description %>
		<%= f.text_area :description, size: "60x12" %>
	</div>

	<div class="form-group">
		<%= f.submit %>
	</div>
</ul>
<% end %>

app/views/equipments/edit.html.erb
<h1>Edit Equipment</h1>

<%= render 'form' %>

<%= link_to "Back", equipments_path %>

app/views/equipments/index.html.erb
<h2>Equipment Index</h2>
<ul>
<% @equips.each do |item| %>
	<h5><%= link_to item.name, item %></h5>
	<p>
		<strong>Age Range:</strong> 
		<%= item.age_range %>
	</p>
	<p>
		<strong>Description:</strong> 
		<%= item.description %>
	</p>
<% end %>
</ul>

<%= link_to "Add Equipment", new_equipment_path %>

app/views/equipments/new.html.erb
<h1>Add Equipment</h1>

<%= render 'form' %>

<%= link_to "Back", equipments_path %>

app/views/equipments/show.html.erb
<h1><%= @equip.name %></h1>

<h5>Age Range</h5>

<p><%= @equip.age_range %></p>

<h3>Description</h3>

<p><%= @equip.description %></p>

<%= link_to "Back to Index", equipments_path %>
<% if user_signed_in? %>
	<%= link_to "Edit", edit_equipment_path(@equip) %>

	<% if current_user.admin? %>
		<%= link_to "Delete", equipment_path(@equip),
	method: :delete, data: { confirm: 'Are you sure?' } %>
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Playground</title>
  <!-- gmaps4rails scripts -->
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
	<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.7.0/underscore-min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>

  <link href='http://fonts.googleapis.com/css?family=Fredericka+the+Great|Cabin' rel='stylesheet' type='text/css'/>
  <link src='normalize.css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header>
		<%= render "shared/nav" %>
		<%= render "parks/search" %>
	</header>

	<main>
		<div id='container'>
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>

		<%= yield %>
		</div>
	</main>

</body>

</html>

app/views/parks/_form.html.erb
<%= form_for @park do |f| %>
  <% if @park.errors.any? %>
  <div id="error_explanation">
  <h2><%= pluralize(@park.errors.count, "error") %> prohibited
  this park from being saved:</h2>
	<ul>
	<% @park.errors.full_messages.each do |msg| %>
	<li><%= msg %></li>
	<% end %>
	</ul>
	</div>
	<% end %>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </p>

  <p>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </p>
 
	<p>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </p>

	<p>
    <%= f.label :description %><br>
    <%= f.text_area :description, size: "60x30" %>
  </p>

  <div class="form_group">
<%= collection_check_boxes(:park, :equipment_ids, Equipment.all, :id, :name) %>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/parks/_search.html.erb
<ul id="search">
<%= form_tag(parks_path, method: "get") do %>
  <%= button_tag "Find me!", value: "search" %>
  <%= label_tag(:location, "Search Near:") %>
	<%= text_field_tag(:location, params[:location], placeholder: "City, State")  %>
  <%= label_tag(:distance, "Distance:") %>
	<%= text_field_tag(:distance, params[:distance], placeholder: "5km")  %>
  <%= submit_tag("Search") %>
<% end %>

</ul>

app/views/parks/edit.html.erb
<h1>Edit a Park</h1>

<%= render 'form' %>

<%= link_to "Back", park_path %>

app/views/parks/index.html.erb
<h1>Parks</h1>

<ul>
<% if @message.present? %>
	<h5 class="notice"><%= @message %></h5>
	<p>OR</strong> you could try to increase your distance.<br>Of course, it's also possible your parks haven't been added to the index <em>(so many parks, so little time)</em>, but you can help us by <strong>Adding A Park</strong>! <strong></p>
	<% elsif @request.present? %>
	<p class="notice"><%= @request %></p>
<% end %>

<div style='width: 800px;'>
  <div id="map-canvas" style='width: 300px; height: 200px;'></div>
</div>

<% @parks.each do |park| %>
	<li><strong><%= park.name %></strong>
	<%= park.city %>
		<%= link_to "Show", park_path(park) %>
	<% unless current_user == nil %>
		<% if current_user.admin? %>
			<%= link_to "Edit", edit_park_path(park) %>
			<%= link_to 'Delete', park_path(park),
method: :delete, data: {confirm: "Are your sure?" } %>
	<% end %>
	<% end %>
	</li>

<% end %>
</ul>
<% unless @parks.length == Park.all.length %>
<%= link_to "All Parks", parks_path %>
<% end %>
<%= link_to "Add A Park", new_park_path %>

app/views/parks/new.html.erb
<h1>New Park</h1>

<%= form_for :park, url: parks_path do |f| %>
  <% if @park.errors.any? %>
  <div id="error_explanation">
  <h2><%= pluralize(@park.errors.count, "error") %> prohibited
  this park from being saved:</h2>
	<ul>
	<% @park.errors.full_messages.each do |msg| %>
	<li><%= msg %></li>
	<% end %>
	</ul>
	</div>
	<% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </p>

  <p>
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </p>
 
	<p>
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </p>

	<p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to "Back", parks_path %>

app/views/parks/show.html.erb
<h1><%= @park.name %></h1>


<img src="https://maps.googleapis.com/maps/api/staticmap?center=<%=@park.address%>&zoom=<%= @zoom %> &size=600x300&maptype=roadmap
&markers=color:green%7Clabel:X%7C<%= @park.latitude %>,<%= @park.longitude %>"><br>


<h3><%= @park.address %><br>
<%= @park.city %>, <%= @park.state %></h3>


<h4>Description:</h4>
<p><%= @park.description %></p>

<h4>Equipment:</h4>
<% @park.equipments.each do |item| %>
<li>
<% if item.id? %>
<%= link_to item.name, equipments_path(item.id) %>
<% else %>
<%= item.name %>
<% end %>
</li>
<% end %>

<h5>Nearby Parks</h5>
<ul>
	<% @park.nearbys(5).each do |nearby_park| %>
		<li><%= link_to nearby_park.name, nearby_park %></li>
	<% end %>
</ul>

<h2>Comments</h2>

<%= render @park.comments %>


<h2>Add a comment:</h2>

<%= render 'comments/form' %>

<% unless current_user == nil %>
	<% if current_user.admin? %>

	<%= link_to "Edit", edit_park_path(@park) %>
	<%= link_to 'Delete', park_path(@park),
method: :delete, data: {confirm: "Are your sure?" } %>
	<% end %>
<% end %>
<%= link_to "Back", parks_path %>

app/views/shared/_nav.html.erb
<ul>

<li><%= link_to "Home", root_path %></li>

<li><%= link_to "Parks", parks_path %></li>

<li><%= link_to "Equipment List", equipments_path %></li>

<% if signed_in? %>

<li id="sign_in">Signed in as: <%= current_user.username %></li>

<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
<% else %>

<li><%= link_to "Sign In", new_user_session_path %></li>

<li><%= link_to "Sign Up", new_user_registration_path %></li>

<% end %>
</ul>

app/views/welcome/index.html.erb
<h1>Play Time!</h1>

<img src="http://www.weekendnotes.com/im/005/05/glebe-park-civic-canberra-playgrounds-fun-for-chil21.jpg" width="50%">

<h3>About</h3>

<p>This site aims to catalog parks and playgrounds with the hope of creating an index of parks out there so that users can better select child-appropriate places for play based on equipment, descriptions, ratings and comments.</p>

<h2>Help us grow the project!</h2>

<%= link_to 'Parks Index', controller: 'parks' %> 